on: [push]

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    name: dotnet-build
    steps:
      - uses: actions/checkout@v2
      - uses: ohpensource/platform-cicd-scripts/platform-cicd-scripts/builds/dotnet@0.4.2.1
        with:
          app-path: "src/dotnet"
